const actions = {
  GET_EVENT_DETAIL: 'GET_EVENT_DETAIL',
  GET_TRAINER_DETAIL: 'GET_TRAINER_DETAIL',
  GET_ROOM_DETAIL: 'GET_ROOM_DETAIL',
  GET_VIDEO_CLASS_DETAIL: 'GET_VIDEO_CLASS_DETAIL',
  GET_CLASSROOM: 'GET_CLASSROOM'
}

export default actions;